import { SummitDemoScenario } from "./summitEvents";
import { summitDemoPatient } from "./summitMockData";

const baseStart = [
  { offsetMs: 0, event: { type: "session", status: "starting", label: "Creating mock LiveKit room" } },
  { offsetMs: 450, event: { type: "latency", stage: "room_connect", valueMs: 312, targetMs: 500 } },
  { offsetMs: 700, event: { type: "session", status: "connected", label: "Caller and Summit agent connected" } },
  { offsetMs: 1000, event: { type: "session", status: "running", label: "Demo trace running" } },
  { offsetMs: 1250, event: { type: "transcript", speaker: "agent", text: "Thank you for calling Summit Orthopedics. I can help with scheduling or route you to the right team. How can I help today?", isFinal: true, confidence: 0.99 } },
] satisfies SummitDemoScenario["events"];

const ended = (offsetMs: number, label = "Demo trace complete") => ({
  offsetMs,
  event: { type: "session", status: "ended", label },
} satisfies SummitDemoScenario["events"][number]);

export const summitDemoScenarios: SummitDemoScenario[] = [
  {
    id: "normal_scheduling_knee",
    label: "Normal scheduling - knee",
    description: "Existing patient requests a knee appointment and confirms a review-ready slot.",
    expectedOutcome: "Appointment draft enters staff review after explicit confirmation.",
    events: [
      ...baseStart,
      { offsetMs: 1900, event: { type: "transcript", speaker: "caller", text: "Hi, I need to schedule an appointment for knee pain.", isFinal: true, confidence: 0.96 } },
      { offsetMs: 2200, event: { type: "latency", stage: "stt_final", valueMs: 118, targetMs: 150 } },
      { offsetMs: 2500, event: { type: "intent", intent: "schedule_existing_patient", confidence: 0.92, reason: "Caller asks for an orthopedic appointment and gives a body-part reason." } },
      { offsetMs: 2900, event: { type: "transcript", speaker: "agent", text: "I can help with that. Are you a new patient, or have you been seen by Summit before?", isFinal: true, confidence: 0.99 } },
      { offsetMs: 3600, event: { type: "transcript", speaker: "caller", text: "I've been there before. My name is Jordan Ellis, date of birth April twelfth, nineteen seventy one.", isFinal: true, confidence: 0.94 } },
      { offsetMs: 3950, event: { type: "tool", tool: "lookup_patient", status: "requested", input: { name: summitDemoPatient.name, dob: summitDemoPatient.dob } } },
      { offsetMs: 4200, event: { type: "policy", gate: "identity_confirmation", decision: "pass", reason: "Name and DOB were captured with sufficient confidence for a demo lookup." } },
      { offsetMs: 4400, event: { type: "tool", tool: "lookup_patient", status: "running" } },
      { offsetMs: 4820, event: { type: "tool", tool: "lookup_patient", status: "succeeded", latencyMs: 418, output: { patientId: summitDemoPatient.patientId, matchStatus: summitDemoPatient.matchStatus } } },
      { offsetMs: 5100, event: { type: "tool", tool: "get_provider_availability", status: "requested", input: { bodyPart: "knee", providerGroup: "Hip and knee" } } },
      { offsetMs: 5350, event: { type: "tool", tool: "get_provider_availability", status: "succeeded", latencyMs: 342, output: { provider: "Dr. Chen", location: "Summit Main", slot: "Tuesday 10:30 AM" } } },
      { offsetMs: 5600, event: { type: "latency", stage: "tool_roundtrip", valueMs: 342, targetMs: 600 } },
      { offsetMs: 5900, event: { type: "transcript", speaker: "agent", text: "I found an opening with Dr. Chen at Summit Main on Tuesday at 10:30 AM. Would you like me to prepare that for staff review?", isFinal: true, confidence: 0.99 } },
      { offsetMs: 6900, event: { type: "transcript", speaker: "caller", text: "Yes, that works.", isFinal: true, confidence: 0.98 } },
      { offsetMs: 7200, event: { type: "policy", gate: "appointment_confirmation", decision: "pass", reason: "Caller explicitly confirmed the offered provider, location, and time." } },
      { offsetMs: 7500, event: { type: "tool", tool: "prepare_appointment_for_review", status: "approved", input: { patientId: summitDemoPatient.patientId, provider: "Dr. Chen", slot: "Tuesday 10:30 AM", reason: "knee pain" } } },
      { offsetMs: 7900, event: { type: "tool", tool: "prepare_appointment_for_review", status: "succeeded", latencyMs: 276, output: { reviewId: "REV-1042", status: "needs_review" } } },
      { offsetMs: 8200, event: { type: "review", status: "needs_review", summary: "Appointment draft prepared for staff review.", payload: { patient: summitDemoPatient.name, provider: "Dr. Chen", location: "Summit Main", slot: "Tuesday 10:30 AM", reason: "Knee pain", routingBasis: "body part routing" } } },
      { offsetMs: 8500, event: { type: "latency", stage: "eot_to_audio", valueMs: 642, targetMs: 700 } },
      { offsetMs: 8800, event: { type: "transcript", speaker: "agent", text: "Great. I prepared that appointment for staff review. The office can confirm it after checking the schedule record.", isFinal: true, confidence: 0.99 } },
      ended(9800),
    ],
  },
  {
    id: "workers_comp_transfer",
    label: "Workers comp hard transfer",
    description: "Caller reveals the injury happened at work.",
    expectedOutcome: "Scheduling is blocked and the call transfers to the workers compensation coordinator.",
    events: [
      ...baseStart,
      { offsetMs: 1900, event: { type: "transcript", speaker: "caller", text: "I hurt my shoulder at work and need to make an appointment.", isFinal: true, confidence: 0.97 } },
      { offsetMs: 2250, event: { type: "intent", intent: "workers_comp", confidence: 0.98, reason: "Caller explicitly describes a work injury." } },
      { offsetMs: 2600, event: { type: "failure", scenario: "workers_comp_transfer", label: "Workers comp detected", expectedBehavior: "Scheduling tools must be unavailable while this flag is active." } },
      { offsetMs: 2950, event: { type: "policy", gate: "workers_comp_block", decision: "transfer", reason: "Workers compensation scheduling is excluded from MVP scope." } },
      { offsetMs: 3300, event: { type: "tool", tool: "transfer_call", status: "approved", input: { destination: "workers compensation coordinator", reason: "work injury" } } },
      { offsetMs: 3650, event: { type: "tool", tool: "transfer_call", status: "succeeded", latencyMs: 231, output: { queue: "WC_COORDINATOR", mode: "warm transfer simulation" } } },
      { offsetMs: 4000, event: { type: "review", status: "transferred", summary: "Call transferred. No appointment draft created.", payload: { destination: "workers compensation coordinator", blockedTools: ["lookup_patient", "get_provider_availability", "prepare_appointment_for_review"] } } },
      { offsetMs: 4400, event: { type: "transcript", speaker: "agent", text: "Because this is related to a work injury, I need to route you to the workers compensation coordinator so the authorization and claim details are handled correctly. I will transfer you now.", isFinal: true, confidence: 0.99 } },
      ended(5600),
    ],
  },
  {
    id: "medical_question_escalation",
    label: "Medical question escalation",
    description: "Caller asks for medical guidance about symptoms.",
    expectedOutcome: "Agent refuses medical advice, captures caller words, and creates a clinical callback task.",
    events: [
      ...baseStart,
      { offsetMs: 1900, event: { type: "transcript", speaker: "caller", text: "My knee is swollen and painful. Should I take something or is that dangerous?", isFinal: true, confidence: 0.95 } },
      { offsetMs: 2250, event: { type: "intent", intent: "medical_question", confidence: 0.96, reason: "Caller asks for symptom interpretation and medication guidance." } },
      { offsetMs: 2600, event: { type: "policy", gate: "medical_advice_block", decision: "reject", reason: "The agent cannot provide clinical advice or medication guidance." } },
      { offsetMs: 3000, event: { type: "tool", tool: "log_patient_statement", status: "approved", input: { patientWords: "My knee is swollen and painful. Should I take something or is that dangerous?" } } },
      { offsetMs: 3350, event: { type: "tool", tool: "log_patient_statement", status: "succeeded", latencyMs: 188, output: { statementId: "STMT-778" } } },
      { offsetMs: 3650, event: { type: "tool", tool: "create_staff_task", status: "approved", input: { taskType: "clinical_callback", urgencyFlags: ["swelling", "pain"] } } },
      { offsetMs: 4050, event: { type: "tool", tool: "create_staff_task", status: "succeeded", latencyMs: 304, output: { taskId: "TASK-3091", queue: "clinical team" } } },
      { offsetMs: 4350, event: { type: "review", status: "escalated", summary: "Clinical callback task created. No medical advice given.", payload: { queue: "clinical team", urgencyFlags: ["swelling", "pain"], adviceProvided: false } } },
      { offsetMs: 4700, event: { type: "transcript", speaker: "agent", text: "I cannot provide medical advice, but I can take down your message and route it to the clinical team for review. If you believe this is urgent, please seek immediate medical care.", isFinal: true, confidence: 0.99 } },
      ended(5900),
    ],
  },
  {
    id: "ambiguous_provider_name",
    label: "Ambiguous provider name",
    description: "Caller says a provider name that sounds like Chen or Cohen.",
    expectedOutcome: "Agent clarifies before any scheduling lookup runs.",
    events: [
      ...baseStart,
      { offsetMs: 1900, event: { type: "transcript", speaker: "caller", text: "I was referred to Doctor Ch-... I think Chen or Cohen.", isFinal: true, confidence: 0.62 } },
      { offsetMs: 2300, event: { type: "intent", intent: "referred_provider", confidence: 0.74, reason: "Caller references a provider but STT confidence is below safe threshold." } },
      { offsetMs: 2650, event: { type: "failure", scenario: "ambiguous_provider_name", label: "Provider ambiguity", expectedBehavior: "Agent asks for clarification and blocks provider availability lookup." } },
      { offsetMs: 3000, event: { type: "policy", gate: "low_confidence_block", decision: "clarify", reason: "Provider name confidence is too low for routing." } },
      { offsetMs: 3350, event: { type: "transcript", speaker: "agent", text: "I may have misheard the provider name. Did you say Dr. Chen, the hip and knee provider, or Dr. Cohen, the hand and wrist provider?", isFinal: true, confidence: 0.99 } },
      { offsetMs: 4300, event: { type: "review", status: "none", summary: "Waiting for clarification before tools run.", payload: { blockedTool: "get_provider_availability", reason: "ambiguous provider" } } },
      ended(5200),
    ],
  },
  {
    id: "ecw_timeout",
    label: "eCW timeout",
    description: "The mock EHR lookup fails and forces staff review.",
    expectedOutcome: "Agent creates a staff callback task instead of pretending the lookup succeeded.",
    events: [
      ...baseStart,
      { offsetMs: 1900, event: { type: "transcript", speaker: "caller", text: "Can you check if Dr. Park has anything open next week?", isFinal: true, confidence: 0.94 } },
      { offsetMs: 2250, event: { type: "intent", intent: "schedule_existing_patient", confidence: 0.88, reason: "Caller asks for provider availability." } },
      { offsetMs: 2600, event: { type: "tool", tool: "get_provider_availability", status: "requested", input: { provider: "Dr. Park", dateRange: "next week" } } },
      { offsetMs: 3000, event: { type: "tool", tool: "get_provider_availability", status: "running" } },
      { offsetMs: 4700, event: { type: "tool", tool: "get_provider_availability", status: "failed", latencyMs: 1708, reason: "Simulated eCW timeout" } },
      { offsetMs: 5000, event: { type: "policy", gate: "human_review_required", decision: "review", reason: "Schedule read failed. Agent cannot invent availability." } },
      { offsetMs: 5350, event: { type: "tool", tool: "create_staff_task", status: "succeeded", latencyMs: 249, output: { taskId: "TASK-4088", queue: "scheduling callback" } } },
      { offsetMs: 5650, event: { type: "review", status: "needs_review", summary: "Staff callback required because schedule lookup timed out.", payload: { provider: "Dr. Park", requestedRange: "next week", reason: "eCW timeout" } } },
      { offsetMs: 6000, event: { type: "transcript", speaker: "agent", text: "I am having trouble seeing the schedule right now, so I am creating a staff callback task rather than guessing. The office can call you back with confirmed availability.", isFinal: true, confidence: 0.99 } },
      ended(7200),
    ],
  },
  {
    id: "unavailable_slot",
    label: "Unavailable slot",
    description: "Requested appointment time is unavailable.",
    expectedOutcome: "Agent offers alternatives and does not create an appointment draft until a slot is accepted.",
    events: [
      ...baseStart,
      { offsetMs: 1900, event: { type: "transcript", speaker: "caller", text: "I need Dr. Chen this Friday morning for my knee.", isFinal: true, confidence: 0.95 } },
      { offsetMs: 2250, event: { type: "intent", intent: "schedule_existing_patient", confidence: 0.9, reason: "Caller requests a specific provider and time window." } },
      { offsetMs: 2600, event: { type: "tool", tool: "get_provider_availability", status: "requested", input: { provider: "Dr. Chen", requestedWindow: "Friday morning" } } },
      { offsetMs: 3100, event: { type: "tool", tool: "get_provider_availability", status: "succeeded", latencyMs: 386, output: { requestedAvailable: false, alternatives: ["Monday 2:15 PM", "Tuesday 10:30 AM"] } } },
      { offsetMs: 3450, event: { type: "policy", gate: "appointment_confirmation", decision: "clarify", reason: "Requested slot unavailable. Caller must accept an alternative before review creation." } },
      { offsetMs: 3800, event: { type: "transcript", speaker: "agent", text: "I do not see Friday morning available with Dr. Chen. I can offer Monday at 2:15 PM or Tuesday at 10:30 AM, or I can create a staff callback task.", isFinal: true, confidence: 0.99 } },
      { offsetMs: 4550, event: { type: "review", status: "none", summary: "No appointment draft created because no alternative was accepted yet.", payload: { requestedWindow: "Friday morning", alternatives: ["Monday 2:15 PM", "Tuesday 10:30 AM"] } } },
      ended(5600),
    ],
  },
  {
    id: "slow_elderly_caller",
    label: "Slow elderly caller",
    description: "Caller pauses while providing date of birth and details.",
    expectedOutcome: "Agent waits, reassures, and confirms before taking action.",
    events: [
      ...baseStart,
      { offsetMs: 1900, event: { type: "transcript", speaker: "caller", text: "I need... uh... an appointment with... I think... Doctor Adams.", isFinal: true, confidence: 0.84 } },
      { offsetMs: 2300, event: { type: "latency", stage: "stt_final", valueMs: 286, targetMs: 150 } },
      { offsetMs: 2600, event: { type: "intent", intent: "schedule_existing_patient", confidence: 0.82, reason: "Caller likely needs scheduling but spoke slowly with pauses." } },
      { offsetMs: 3000, event: { type: "transcript", speaker: "agent", text: "No problem, take your time. I heard Dr. Adams. Can you please tell me your name and date of birth?", isFinal: true, confidence: 0.99 } },
      { offsetMs: 4300, event: { type: "transcript", speaker: "caller", text: "It is Jordan... Ellis... April... twelfth... nineteen seventy one.", isFinal: true, confidence: 0.86 } },
      { offsetMs: 4700, event: { type: "policy", gate: "identity_confirmation", decision: "clarify", reason: "DOB confidence is acceptable for readback, not enough for action without confirmation." } },
      { offsetMs: 5050, event: { type: "transcript", speaker: "agent", text: "Thank you. I heard Jordan Ellis, date of birth April 12, 1971. Is that correct?", isFinal: true, confidence: 0.99 } },
      { offsetMs: 5750, event: { type: "latency", stage: "eot_to_audio", valueMs: 1190, targetMs: 700 } },
      { offsetMs: 6100, event: { type: "review", status: "none", summary: "Agent remained in confirmation mode. No irreversible action taken.", payload: { reason: "slow caller confirmation loop", irreversibleActionTaken: false } } },
      ended(7200),
    ],
  },
  {
    id: "billing_transfer",
    label: "Billing transfer",
    description: "Caller needs help with a bill, outside scheduling scope.",
    expectedOutcome: "Agent transfers to billing and does not run scheduling tools.",
    events: [
      ...baseStart,
      { offsetMs: 1900, event: { type: "transcript", speaker: "caller", text: "I am calling about a bill I got in the mail.", isFinal: true, confidence: 0.97 } },
      { offsetMs: 2250, event: { type: "intent", intent: "billing", confidence: 0.98, reason: "Caller asks about a bill." } },
      { offsetMs: 2600, event: { type: "policy", gate: "billing_scope", decision: "transfer", reason: "Billing belongs to the RCM queue and is outside scheduling scope." } },
      { offsetMs: 2950, event: { type: "tool", tool: "transfer_call", status: "approved", input: { destination: "billing RCM queue", reason: "billing question" } } },
      { offsetMs: 3300, event: { type: "tool", tool: "transfer_call", status: "succeeded", latencyMs: 244, output: { queue: "BILLING_RCM", mode: "warm transfer simulation" } } },
      { offsetMs: 3650, event: { type: "review", status: "transferred", summary: "Billing call transferred. No scheduling tools executed.", payload: { destination: "billing RCM queue", schedulingToolsExecuted: false } } },
      { offsetMs: 3950, event: { type: "transcript", speaker: "agent", text: "I can route you to the billing team so they can help with that statement. I will transfer you now.", isFinal: true, confidence: 0.99 } },
      ended(5100),
    ],
  },
];

export const defaultSummitScenarioId = "normal_scheduling_knee" as const;

export function getSummitScenario(id: string): SummitDemoScenario {
  return summitDemoScenarios.find((scenario) => scenario.id === id) ?? summitDemoScenarios[0];
}
